FROM devbfvio/openedge-compiler:OPENEDGEVERSION

USER root

RUN apt-get update \
  && apt-get install -y wget apt-transport-https software-properties-common python3 python3-pip \
  && wget https://packages.microsoft.com/config/ubuntu/24.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb \
  && dpkg -i packages-microsoft-prod.deb \
  && rm packages-microsoft-prod.deb \
  && apt-get update \
  && apt-get install -y dotnet-runtime-8.0 \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

RUN \
sed -i "s/net6\.0/net8\.0/g" /usr/dlc/bin/Progress.clrbridge.netcore.runtimeconfig.json && \
  sed -i "s/6\.0\.0/8\.0\.0/g" /usr/dlc/bin/Progress.clrbridge.netcore.runtimeconfig.json

USER openedge
