name: CI 

on: 
  [ push, workflow_dispatch ]

permissions:
  contents: read
  packages: read
      
jobs:
  build:
    
    runs-on: ubuntu-20.04
    
    strategy:
      matrix:
        version: [ 12.7.0 ]
    
    steps:

      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8         # v3.1.0
        with:
          path: src

      - name: download installer files
        run: |
          docker run -d defbfvio/oe-install:${{matrix.version}}
      
      