name: CI 

on: 
  [ push, workflow_dispatch ]

permissions:
  contents: read
  packages: read
      
jobs:
  build:
    
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        version: [ 12.8.12, 13.0.0 ]
    
    steps:

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          path: src

      - name: Get OpenEdge version
        id: get-oeversion
        uses: bfv/openedge-flatversion@cd00d571e79c7a7be1d1d0ecce22febb2fb7dd0c  # v1.2.3
        with:
          version: ${{matrix.version}}

      - name: Version to env
        run: |
          echo "FLATVERSION=${{ steps.get-oeversion.outputs.flat-version }}" >> $GITHUB_ENV
          echo "OPENEDGE_VERSION=${{matrix.version}}" >> $GITHUB_ENV
          echo "OPENEDGE_BASE_VERSION=${{ steps.get-oeversion.outputs.base-version }}" >> $GITHUB_ENV

      - name: Insert JDK version in Dockerfile
        run: |
          jdk=`jq -r ".jdk${{env.FLATVERSION}}" src/jdk-versions.json`
          echo JDK: $jdk
          sed -i "s/JDKVERSION/$jdk/g" src/Dockerfile
          echo download jdk from Dockerfile:
          cat src/Dockerfile | grep temurin
  
      - name: Download installer files
        run: |
          src/scripts/download-openedge.sh
      
      - name: Get response.ini  # get progress.cfg from secret PROGRESS_CFG_122
        run: |
          echo fetching response.ini/progress.cfg from secret RESPONSE_INI_${{env.FLATVERSION}}
          echo "${{ secrets[format('RESPONSE_INI_{0}', env.FLATVERSION)] }}" > src/response.ini
          echo "${{ secrets[format('PROGRESS_CFG_{0}', env.FLATVERSION)] }}" | base64 --decode > src/progress.cfg
          ls -l src

      - name: Prepare Dockerfile-dotnet
        run: |
          oever=$OPENEDGE_VERSION
          sed -i "s/OPENEDGEVERSION/$oever/g" src/Dockerfile-dotnet
          cat src/Dockerfile-dotnet
  
      - name: Build plain docker image
        run: |
          cd src
          docker build -t devbfvio/openedge-compiler:${{env.OPENEDGE_VERSION}} .
      
      - name: Build dotnet docker image
        run: |
          cd src
          docker build -t devbfvio/openedge-compiler:${{env.OPENEDGE_VERSION}}-dotnet10 -f Dockerfile-dotnet .

      - name: Remove installer files
        run: |
          cd src
          rm -f PROGRESS_*
          rm response.ini
          ls -l 
      
      - name: Execute test build
        run: |
          ls -l 
          mkdir artifacts
          chmod ugo=rwx -R ${PWD}/artifacts 
          chmod u=rwx,og=rx -R ${PWD}/src   # don't write to src!
          docker run \
            -v ${PWD}/src/src:/app/src \
            -v ${PWD}/artifacts:/artifacts \
            -v ${PWD}/src/progress.cfg:/usr/dlc/progress.cfg \
            devbfvio/openedge-compiler:${{env.OPENEDGE_VERSION}} \
            /app/src/scripts/build.sh
          ls -l artifacts
          cat artifacts/sports2020.rcode.list

      - name: Execute dotnet test
        run: |
          docker run \
            -v ${PWD}/src/src:/app/src \
            -v ${PWD}/src/progress.cfg:/usr/dlc/progress.cfg \
            devbfvio/openedge-compiler:${{env.OPENEDGE_VERSION}}-dotnet10 \
            /usr/dlc/bin/_progres -b -p /app/src/dotnet-validate.p

      # generate SBOM's

      - name: Install cosign
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6  # v4.1.2
        with:
          cosign-release: 'v3.1.3'

      - name: Generate SBOM (CycloneDX JSON)
        uses: anchore/sbom-action@3ad7283483fc7af8ff2b4ea19663c2d5ca935e26  # v0.24.2
        with:
          image: devbfvio/openedge-compiler:${{env.OPENEDGE_VERSION}}
          format: cyclonedx-json
          artifact-name: devbfvio-openedge-compiler-${{env.OPENEDGE_VERSION}}.cyclonedx.json

      - name: Generate SBOM (SPDX JSON)
        uses: anchore/sbom-action@3ad7283483fc7af8ff2b4ea19663c2d5ca935e26  # v0.24.2
        with:
          image: devbfvio/openedge-compiler:${{env.OPENEDGE_VERSION}}
          format: spdx-json
          artifact-name: devbfvio-openedge-compiler-${{env.OPENEDGE_VERSION}}.spdx.json
