name: CI 

on: 
  [ push, workflow_dispatch ]

permissions:
  contents: read
  packages: read
      
jobs:
  build:
    
    runs-on: ubuntu-20.04
    
    strategy:
      matrix:
        version: [ 12.7.0 ]
    
    steps:

      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8         # v3.1.0
        with:
          path: src

      - name: Download installer files
        run: |
          docker run -d devbfvio/oeinstaller:${{matrix.version}}
      
      - name: Get version info
        run: |
          v=${{matrix.version}}
          flatversion=`echo ${v%\.*} | sed "s/\.//g"`
          echo flattened minor version: $flatversion
          echo "FLATVERSION=${flatversion}" >> $GITHUB_ENV
          echo "OPENEDGE_VERSION=${{matrix.version}}" >> $GITHUB_ENV
        