name: test

on: workflow_dispatch 

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8         # v3.1.0
        with:
          path: src
      
      - name: Get JDK version
        run: |
          jdk=`jq -r '.jdk127' src/jdk-versions.json`
          echo 12.7 JDK: ${jdk}
  
