name: test

on: workflow_dispatch 

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29  # v4.1.6
        with:
          path: src
      
      - name: Get JDK version
        run: |
          jdk=`jq -r '.jdk127' src/jdk-versions.json`
          echo 12.7 JDK: ${jdk}
  
