name: test

on: workflow_dispatch 

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          path: src
      
      - name: Get JDK version
        run: |
          jdk=`jq -r '.jdk127' src/jdk-versions.json`
          echo 12.7 JDK: ${jdk}
  
