name: test

on:
  workflow_dispatch:
    inputs:
      target-registry:
        type: choice
        description: Choose target environment
        #default: "test"
        required: true
        options:
            ${{ env.targets }}

run-name: publish openedge-compiler:${{ inputs.openedgeversion }} 

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - name: first test
        run: |
          echo publish openedge-compiler:${{ github.event.inputs.openedgeversion }}
